on:
  push: 
    branches: 'dev'
  workflow_dispatch: 

name: pipeline
run-name: 这是运行时的名字
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: shell插件
        run: |
          ls -al
          echo ${{github.repository}}
          echo ${{github.ref}}
          echo ${{github.token}}
          echo ${{github.server-url}}
          echo ${{github.server_url}}
      - name: shell2
        run: echo abcd
