on: workflow_dispatch
name: pipeline
run-name: 这是运行时的名字
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shell插件
        run: |
          ls -al
          echo abcd
      - name: shell2
        run: echo abcd
