on: 
  workflow_dispatch：
  push:
    branches: xyz
name: pipeline
run-name: 这是运行时的名字
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: shell插件
        run: |
          ls -al
          echo abcd
      - name: shell2
        run: echo abcd
